### ISSUE TITLE
error: failed retrieving file 'mingw32.db' from 148.251.42.38 : Connection timed out

### ISSUE THREAD

**Issue by AaronNGray** [Alexpux/MSYS2-packages#144]
On doing a 'pacman -Syy' I am getting the following error :-

```
error: failed retrieving file 'mingw32.db' from 148.251.42.38 : Connection timed out after 10000 milliseconds
```

**Comment by Kevin551** [comment]
On doing a 'pacman -Syu' I got the same 3 errors :- but the files downloaded anyway and upon installation the issue has been corrected.
No need to edit /etc/pacman.d/mirrorlist.mingw32

**Comment by elieux** [comment]
Current mirrors should be okay.

**Comment by whitebread** [comment]
I still get the error: impossible to download 'mingw32.db' from repo.msys2.org

**Comment by laurenanyever** [comment]
i'm getting the same error: error: failed retrieving file 'mingw32.db' from repo.msys2.org

**Comment by sarfaraj118** [comment]
Use this 
python -m pip install --upgrade pip
your issue will resolve ....

**Comment by sarfaraj118** [comment]
step to solve the isssue ...
1. pip install packagename --upgrade --ignore-installed
2. pacman -S mingw-w64-i686-python2-cryptography

**Comment by karippery** [comment]
when i  use $ pacman -Syu
i got error like this error: failed retrieving file 'mingw32.db' from 148.251.42.38 : Connection timed out after 10000 milliseconds
could you please explain why?﻿

**Comment by StarWolf3000** [comment]
@karippery How old is your mirrorlist? As from what I've found on the net, this server is long gone. Check your `/etc/pacman.d/mirrorlist.msys2`, `/etc/pacman.d/mirrorlist.mingw32` and `/etc/pacman.d/mirrorlist.mingw64`.

**Comment by karippery** [comment]
Thank you

I got solution. It was a Proxy Problem. When i add proxys in profile file. Error is gone. 
You can close this

**Comment by wuyuansu** [comment]
me too.close the proxy,and it goes well

**Comment by B1Z0N** [comment]
I'll just leave it here: 

https://stackoverflow.com/questions/69348953/certificate-error-when-trying-to-install-msys2-packages-on-windows-server
